### ISSUE TITLE
NPM module

### ISSUE THREAD

**Issue by reverofevil** [graniteds/jsonr#2]
The previous ticket with the same name was created for some unclear reasons, but

Why don't you make an `npm` module? That needs `npm init` only, with `jsonr-module.js` being set as entry point.

JSONR looks like it's quite stable, as it serialized/deserialized several quite complex abstract syntax trees with no single error ("stable" `circular-json` didn't).

**Comment by fwolff** [comment]
Done. You should be able to get the module with the following command:

``` bash
$ npm install jsonr
```

Quick and dirty though, I'm pretty sure I didn't do it the clean way, tell me if something goes wrong.

Thanks for the nice feedback anyway!

**Comment by reverofevil** [comment]
Tested. Worked like a charm. Thank you!

**Comment by fwolff** [comment]
Nice! Feel free to star the project on NPM: https://www.npmjs.org/package/jsonr ;)

**Comment by reverofevil** [comment]
Starred :)

2014-10-21 14:16 GMT+04:00 Franck Wolff notifications@github.com:
